export const SET_TOKEN = "SET_TOKEN"
export const LOGOUT = "LOGOUT"

export const CREATE_QUESTION = "CREATE_QUESTION"
export const UPDATE_QUESTION = "UPDATE_QUESTION"
export const GET_QUESTIONS_REQUEST = "GET_QUESTIONS_REQUEST"
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS"
export const GET_QUESTIONS_FAILURE = "GET_QUESTIONS_FAILURE"

export const REQUEST_NOT_INITIATED = "REQUEST_NOT_INITIATED"
export const REQUEST_INITIATED = "REQUEST_INITIATED"
export const REQUEST_SUCCESS = "REQUEST_SUCCESS"
export const REQUEST_FAILURE = "REQUEST_FAILURE"
